openapi: 3.0.2
info:
  description: "This is participant state changer adapter API"
  title: Participant state changer API
  version: 0.1.0

servers:
  - url: '{protocol}://{server}:{port}'
    variables:
      protocol:
        enum:
          - 'http'
        default: 'http'
      server:
        default: 'localhost'
      port:
        enum:
          - '80'
        default: '80'

tags:
  - name: Participant state
    description: Allows to control state of the participant on the call

paths:
  "/v1/participants":
    post:
      tags:
        - Participant state
      operationId: addParticipant
      description: add new participant to the call

      requestBody:
        $ref: '#/components/requestBodies/Participant'

      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AcceptedResponse"
        "400":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  "/v1/calls/{callId}/participants/{participantId}:delete":
    post:
      tags:
        - Participant state
      operationId: removeParticipant
      description: remove participant from the call

      parameters:
        - $ref: '#/components/parameters/participantId'
        - $ref: '#/components/parameters/callId'

      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AcceptedResponse"
        "400":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  parameters:
    callId:
      name: callId
      description: "The unique 36 character id that represents the call"
      required: true
      in: path
      schema:
        type: string
        minLength: 36
        maxLength: 36
        example: "bea76b16-5aff-4cd6-8db0-5d8d649dd865"
    participantId:
      name: participantId
      description: "The unique 36 character id that represents the participant"
      required: true
      in: path
      schema:
        type: string
        minLength: 36
        maxLength: 36
        example: "bea76b16-5aff-4cd6-8db0-5d8d649dd865"
  requestBodies:
    Participant:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Participant'
      required: true
      description: participant metadata

  schemas:
    Participant:
      type: object
      description: participant metadata
      required:
        - id
      properties:
        id:
          type: string
          description: participant id
        callId:
          type: string
          description: call id
        name:
          type: string
          description: participant autodetected name

    ErrorResponse:
      type: object
      required:
        - code
        - message
        - detail
        - timestamp
      properties:
        code:
          type: string
          description: Error code that identifies the unexpected condition
        message:
          type: string
          description: Human readable error message
        details:
          type: string
          description: Detailed error message describing the cause
        timestamp:
          type: string
          format: date-time
          description: Error timestamp

    AcceptedResponse:
      type: string
      description: Message to confirm that reqest accepted succesfull
